### ISSUE TITLE
Confirm settings for config file

### ISSUE THREAD

**Issue by stevenday** [mysociety/panama-theme#50]
Settings that I can see which Panama may want to change:

``` YAML
# Site name appears in various places throughout the site
SITE_NAME: 'Alaveteli'
```

``` YAML
# These feeds are displayed accordingly on the Alaveteli "blog" page:
BLOG_FEED: ''
TWITTER_USERNAME: ''
# Set the widget_id to get the Twitter sidebar on the blog page.
# To get one https://twitter.com/settings/widgets
TWITTER_WIDGET_ID: ''
```

``` YAML
# How many days should have passed before an answer to a request is officially late?
REPLY_LATE_AFTER_DAYS: 20
REPLY_VERY_LATE_AFTER_DAYS: 40
# We give some types of authority like schools a bit longer than everyone else
SPECIAL_REPLY_VERY_LATE_AFTER_DAYS: 60
# Whether the days above are given in working or calendar days. Value can be "working" or "calendar".
# Default is "working".
WORKING_OR_CALENDAR_DAYS: working
```

``` YAML
# example public bodies for the home page, semicolon delimited - short_names
# Comment out if you want this to be auto-generated. WARNING: this is slow & don't use production!
FRONTPAGE_PUBLICBODY_EXAMPLES: 'tgq'
```

``` YAML
# Whether a user needs to sign in to start the New Request process
FORCE_REGISTRATION_ON_NEW_REQUEST: false
```

``` YAML
# Number of days after which to send a 'new response reminder'
NEW_RESPONSE_REMINDER_AFTER_DAYS: [3, 10, 24]
```

``` YAML
# This rate limiting can be turned off per-user via the admin interface
MAX_REQUESTS_PER_USER_PER_DAY: 6
```

There's also a couple of api keys we'll need to set up, for Google Analytics and Recaptcha.
